version = "1.0"

[main]
name = "MyTinyTodo configuration"

    [main.config]
    name = "Configuration Options"

        [main.config.title]
        ask = "Set title"
        type = "string"
        help = "Specify a title for your todolist."
        bind = "title:__FINALPATH__/db/config.php"

        [main.config.set_password]
        ask = "Set password"
        type = "password"
        help = "Specify password here to protect your tasks from modification, or leave empty that everyone could read/write todolist."
        bind = "password:__FINALPATH__/db/config.php"

    [main.php_fpm_config]
    name = "PHP-FPM configuration"

        [main.php_fpm_config.fpm_footprint]
        ask = "Memory footprint of the service?"
        choices = ["low", "medium", "high", "specific"]
        default = "low"
        help = "low <= 20Mb per pool. medium between 20Mb and 40Mb per pool. high > 40Mb per pool.<br>Use specific to set a value with the following option."

        [main.php_fpm_config.free_footprint]
        ask = "Memory footprint of the service?"
        type = "number"
        default = "0"
        help = "Free field to specify exactly the footprint in Mb if you don't want to use one of the three previous values."

        [main.php_fpm_config.fpm_usage]
        ask = "Expected usage of the service?"
        choices = ["low", "medium", "high"]
        default = "low"
        help = "low: Personal usage, behind the sso. No RAM footprint when not used, but the impact on the processor can be high if many users are using the service.<br>medium: Low usage, few people or/and publicly accessible. Low RAM footprint, medium processor footprint when used.<br>high: High usage, frequently visited website. High RAM footprint, but lower on processor usage and quickly responding."
