#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    # test_upgrade_from.b598d723.name = "Upgrade from 1.6.4"
    test_upgrade_from.a6ceeb181da7f3236a115bcb63c5c7ee4ceed68c.name = "Upgrade from 1.8.1~ynh3"
